---
- hosts: all
  become_user: yes
  become_method: sudo
  gather_facts: yes
  tasks:

  - name: update cache
    yum:
      name: "*"
      state: latest
      become: yes
      become_method: sudo
  - name: install OpenJDK
    yum:
      name: java-1.8.0_342-openjdk
      state: latest
      become: yes
      become_method: sudo
  - name: Download the tomcat file
    get_url:
      url: wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
      dest: /tmp
      become: true
      become_method: sudo
  - name: extracting the apache-tomcat-9.0.56.tar.gz
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-9.0.56.tar.gz
      dest: /opt
      remote_src: yes
      become: true
      become_method: sudo


